grafana:
  sidecar:
    datasources:
      config:
        prometheus:
          url: http://prometheus.devenv-prometheus.svc.cluster.local:9090
          uid: prometheus1

  persistence:
    enabled: true
    existingClaim: grafana

  image:
    repository: mikogs/grafana-tweaked-ui
    tag: 9.3.1-3

pvNode: b0fh.f0x.pl
pvDirName: grafana_devenv_pv
svcNodePort: 30104


