apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: {{ .Values.svcNodePort }}
  selector:
    app.kubernetes.io/name: grafana
  type: NodePort
